/* Kasper Studio — data onglet "Copy & Reco" (régénérable, séparée du design)
   Source : docs/analyse-concurrents/*.md (scraping 2026-08-29).
   resultatScore = orientation résultat/business de leur copy (0-10).
   Vert = fort (modèle à apprendre) · Ambre = moyen · Rouge = beauté pure / peu de preuve. */

window.COPY_AGENCES = [
  { id:"ramotion", name:"Ramotion", verticale:"Design", pays:"US (SF)", resultatScore:10, verdict:"Bénéfices (ROI)", prix:"Oui",
    heroVO:"Product & brand design agency — we help executives build impactful brands and drive growth.",
    heroFR:"Agence de design produit & de marque — on aide les dirigeants à bâtir des marques à fort impact et générer de la croissance.",
    lexique:"growth, revenue, exits, valuation, CAC/LTV, measurable results — traduit tout en valeur financière.",
    offres:["Brand Creation (60 K$)","Brand Redesign (85 K$)","Product Redesign (70 K$+)","Product Discovery (25 K$/mo+)","Team Extension (16,8 K$/mo)"],
    forces:["Pricing public en fourchettes + durées (rarissime, énorme confiance)","Chaque réalisation raccrochée à un chiffre business (levée, exit, MAU)","Bandeau chiffres en hero : « 1 Md$ levés · 6 Md$ d'exits »","Segmentation « Votre défi → Notre solution » par persona"],
    faiblesses:["Répétition massive entre pages (remplissage)","Densité froide, peu d'émotion/voix humaine","Prix USD élevés (min 50 K$) peu transposables tels quels"],
    motsRecup:["Traduire chaque livrable en chiffre business","Afficher fourchettes de prix + durées par offre","Offre récurrente packagée (Team Extension → Kasper OS abo)"] },

  { id:"digidop", name:"Digidop", verticale:"Code (Webflow)", pays:"France", resultatScore:9, verdict:"Bénéfices + preuve", prix:"Oui",
    heroVO:"L'agence web des équipes marketing modernes.",
    heroFR:"L'agence web des équipes marketing modernes.",
    lexique:"équipes marketing, à l'ère de l'IA, performance, croissance, conversion, « Human expertise. AI acceleration. »",
    offres:["Marketing Websites","Growth & Performances","Offres sectorielles (Finance/SaaS/Industrie)","IA / AI Automation"],
    forces:["Cible nommée dans le hero (« équipes marketing modernes »)","« Deux offres claires » (créer / faire évoluer) : anti-fouillis","Prix affichés en FAQ (10-30K€ / 30-50K€ / 50-100K€)","Preuve sociale chiffrée par cas (x70 trafic, +43% conv.)"],
    faiblesses:["Mono-techno Webflow","Empilement de sigles (AEO/GEO/CRO/MCP) qui perd un dirigeant","Double claim « n°1 » + « pionnière IA » = auto-proclamé"],
    motsRecup:["« Human expertise. AI acceleration. » → « créa humaine + systèmes automatiques »","« Votre entreprise évolue. Votre site est-il toujours à son image ? »","Afficher des fourchettes de prix pour qualifier"] },

  { id:"bold", name:"Bold Commerce", verticale:"Shopify (SaaS)", pays:"Canada", resultatScore:9, verdict:"Bénéfices (ROI)", prix:"Non",
    heroVO:"Built for the buy-again. (The repeat commerce company)",
    heroFR:"Conçu pour le rachat. (La société du repeat commerce)",
    lexique:"repeat commerce, rétention, valeur client, marge, « acheteurs ponctuels → clients à vie ».",
    offres:["rePete","Subscriptions","Upsell","Custom Pricing","Memberships","Discounts","Maximizers"],
    forces:["Cadre problème/solution : « L'ère de l'acquisition est finie »","Structure « 3 chiffres » (revenir / plus souvent / panier + élevé)","Preuve d'autorité massive (800K marchands, citation Président Shopify)","« Puissantes seules, imbattables ensemble »"],
    faiblesses:["Pas de prix affiché (renvoi App Store / « Let's talk »)","Produit SaaS, pas un concurrent direct","Jargon US SaaS à réadapter au marché FR"],
    motsRecup:["« La croissance que vous cherchez est déjà dans votre liste clients »","« Puissantes seules, imbattables ensemble » pour les 4 piliers","Structure problème → conséquence chiffrée → bénéfice → feature"] },

  { id:"edgarallan", name:"Edgar Allan", verticale:"Code (Webflow)", pays:"US", resultatScore:8, verdict:"Équilibré, orienté résultat", prix:"Non",
    heroVO:"What AI is saying about your brand is now your brand.",
    heroFR:"Ce que l'IA dit de votre marque, c'est désormais votre marque.",
    lexique:"brand + performance, AEO, « prove it works », pipeline, own the category, mesure/data.",
    offres:["Brand to Build","Support & Enablement","Optimization","Answer-Ready Branding","Story Engineering"],
    forces:["Accroche IA forte : « Ce que l'IA dit de vous… »","Réconcilie 2 camps : « beau site sans perf = un beau problème »","Checklist de qualif « Vous êtes au bon endroit si… »","Lead magnet diagnostic gratuit (« AI Brand Score »)"],
    faiblesses:["Jargon dense (AEO, schema, share of voice) pour une PME","Homepage pauvre en texte (JS)","Ancrage Webflow peu transposable"],
    motsRecup:["« Un beau site sans stratégie de perf n'est qu'un beau problème »","Checklist « Vous êtes au bon endroit si… »","Lead magnet : audit/diagnostic gratuit en CTA principal"] },

  { id:"cuberto", name:"Cuberto", verticale:"Créa", pays:"International", resultatScore:8, verdict:"Équilibré (beau + mesurable)", prix:"Partiel",
    heroVO:"Digital design & development agency — for companies ready to move beyond the ordinary.",
    heroFR:"Agence de design & développement digital — pour les entreprises prêtes à dépasser l'ordinaire.",
    lexique:"« beautiful visuals WITH measurable business results », dépasser l'ordinaire, partenariat long terme.",
    offres:["Digital Product Design","Web Design & Development","UX Research & UI Design","Brand Identity","Creative Development"],
    forces:["Promesse « du beau qui rapporte » (beau + mesurable)","5 services titrés + 1 phrase chacun (lisible)","Bloc « Why us » en chiffres (15+ ans, 300+ projets, in-house)","FAQ opérationnelle qui lève les objections"],
    faiblesses:["Hero descriptif générique (« Agence de design & dév »)","Beaucoup de contenu SEO qui dilue le premium","Témoignages parfois interchangeables"],
    motsRecup:["« Des expériences qui convertissent, pas seulement qui impressionnent »","Bloc chiffres de crédibilité (années, projets, in-house)","FAQ anti-objections (délais, tech, budget, process)"] },

  { id:"wemakewebsites", name:"We Make Websites", verticale:"Shopify", pays:"UK", resultatScore:7, verdict:"Bénéfices de réassurance", prix:"Non",
    heroVO:"The Shopify agency for international brands.",
    heroFR:"L'agence Shopify pour les marques internationales.",
    lexique:"design/develop/grow, « safe pair of hands », on time / on budget / maximum impact.",
    offres:["UX/UI Design","Strategy & CRO Insights","Shopify Development","Internationalization","Data Migration","Headless & Composable","Ongoing Success"],
    forces:["Hero limpide : verticale + cible en 1 phrase","Triptyque mémorable « design, develop and grow »","Promesse anti-risque « safe pair of hands / dans les temps, budget, impact »","Endossement massif : citation du Président de Shopify"],
    faiblesses:["Peu de chiffres de résultats clients","Mono-plateforme Shopify (étroit)","CTA faibles (« Say Hello », newsletter), pas de lead magnet"],
    motsRecup:["« On conçoit, on développe et on fait croître votre boutique »","« Une valeur sûre : livré dans les temps, le budget, avec impact »","Distinguer offre « Projet » vs « Succès continu » (retainer)"] },

  { id:"eastsideco", name:"Eastside Co", verticale:"Shopify", pays:"UK", resultatScore:7, verdict:"Bénéfices + relation", prix:"Non",
    heroVO:"Shopify Platinum Partner Agency — from concept to conversion.",
    heroFR:"Agence Shopify Platinum Partner — du concept à la conversion.",
    lexique:"full-service, in-house, « from concept to conversion, and beyond », results-driven, ROI.",
    offres:["Shopify Web Design","Shopify Web Development","Shopify Marketing","Ongoing Shopify Support"],
    forces:["Mur de témoignages authentiques et détaillés","Angle « extension de votre équipe » / « full marketing partner »","« From concept to conversion, and beyond » (parcours complet)","Équipe 100% internalisée (50+) comme différenciateur"],
    faiblesses:["Excès de superlatifs auto-proclamés (« world's most trusted »)","Hero décrit un statut, pas un gain client","Aucun prix ni cadre d'engagement"],
    motsRecup:["« De l'idée à la vente, et au-delà »","« Une extension de votre équipe »","Remplacer les superlatifs par des CHIFFRES (piège à éviter)"] },

  { id:"swanky", name:"Swanky", verticale:"Shopify", pays:"UK/FR", resultatScore:6, verdict:"Équilibré (penché expertise)", prix:"Non",
    heroVO:"Compelling digital experiences for international brands on Shopify Plus.",
    heroFR:"Des expériences digitales percutantes pour les marques internationales sur Shopify Plus.",
    lexique:"migration/replatform, subscription, CRO, data-driven, ROI, funnel, long-term support.",
    offres:["Replatforming to Shopify Plus","Web Design & Development","Subscription Websites","CRO","Digital Marketing","Internationalisation","Ecommerce Branding"],
    forces:["Hero clair : QUI + QUOI + COMMENT en une phrase","Double promesse « migrer PUIS faire grandir »","Chaque service = 1 phrase bénéfice + preuve technique","Verticalisation (« the go-to agency for subscription »)"],
    faiblesses:["Beaucoup de jargon (replatforming, funnel, tech stack)","Aucun prix","CTA répétitifs (« View all » partout)"],
    motsRecup:["« Libérez votre potentiel e-commerce »","« On ne se contente pas de livrer, on fait grandir dans la durée »","« L'agence de référence pour [niche] » (autorité par verticalisation)"] },

  { id:"bonhomme", name:"Bonhomme", verticale:"Design (luxe)", pays:"France", resultatScore:6, verdict:"Équilibré (beau + business)", prix:"Non",
    heroVO:"Agence de branding et web à Paris spécialisée dans les marques premium et luxe.",
    heroFR:"Agence de branding et web à Paris spécialisée dans les marques premium et luxe.",
    lexique:"luxe, désirabilité, excellence, atemporalité + objectifs mesurables, croissance, conversion.",
    offres:["Branding","Digital / Web","Content / Brand content IA"],
    forces:["Liste d'objectifs mesurables (notoriété, croissance, conversion)","Figure de style par oppositions (« la sobriété à l'ostentatoire… »)","Clients prestige nommés + awards chiffrés","IA générative comme offre à part entière"],
    faiblesses:["Copy très dense et sur-optimisée SEO","Ultra-luxe : peu inclusif pour PME/e-com","Peu de résultats chiffrés clients (preuve = awards)"],
    motsRecup:["Structure par oppositions pour définir l'ADN Kasper","« De la stratégie au dev » (intégration bout-en-bout)","Assumer l'IA/brand content comme offre moderne"] },

  { id:"refokus", name:"Refokus", verticale:"Code (Webflow)", pays:"US", resultatScore:5, verdict:"Bénéfices + narratif", prix:"Non",
    heroVO:"The agency founders call when their brand and website need to catch up to the startup they're building.",
    heroFR:"L'agence que les fondateurs appellent quand leur marque doit rattraper la startup qu'ils construisent.",
    lexique:"founders, taste, craft, « same story », point de vue, anti-générique.",
    offres:["Branding","Websites","Brand Marketing"],
    forces:["Accroche par le moment de vie du client (ultra-relatable)","« On aide le monde à voir ce que vous êtes vraiment devenu »","Manifeste en 6 points numérotés (« Refokus Thinking »)","Témoignages longs et spécifiques (anecdotes)"],
    faiblesses:["Aucun chiffre business client (preuve = awards)","Cible très étroite (startups tech / VC)","Trop de texte abstrait sur « taste »/« craft »"],
    motsRecup:["« L'agence que [X] appelle quand [problème précis] »","Manifeste en points numérotés (méthode/convictions)","« Tout doit raconter la même histoire » (cohérence multi-services)"] },

  { id:"instrument", name:"Instrument", verticale:"Créa", pays:"US", resultatScore:5, verdict:"Bénéfices de haut niveau", prix:"Non",
    heroVO:"A technology-led brand, product & marketing agency.",
    heroFR:"Une agence de marque, de produit et de marketing pilotée par la technologie.",
    lexique:"technology-led, caliber, purpose, « every touchpoint tells the same story ».",
    offres:["Brand","Marketing","Product"],
    forces:["Triade claire Brand/Product/Marketing (1 phrase + 2 cas chacune)","Argument d'intégration (« chaque point de contact raconte la même histoire »)","Thought leadership (« Taste is the new competitive advantage »)","Témoignage à fonction précise (Creative Director @ Stripe)"],
    faiblesses:["Homepage maigre en texte (beaucoup de JS)","Discours abstrait/corporate (« shape a better future »)","Aucun résultat chiffré (repose sur les logos)"],
    motsRecup:["Modèle « 1 offre = 1 phrase-bénéfice + 2 cas »","« Chaque point de contact raconte la même histoire »","« Là où la créa rencontre les systèmes/IA »"] },

  { id:"locomotive", name:"Locomotive", verticale:"Design", pays:"Canada", resultatScore:4, verdict:"Bénéfices émotionnels", prix:"Non",
    heroVO:"Digital-first Design Agency — what sets us apart is people.",
    heroFR:"Agence de design digital-first — ce qui nous distingue, ce sont les gens.",
    lexique:"bespoke, sur-mesure, craft, one-stop shop, results-driven, « Triforce ».",
    offres:["Digital (stratégie, UX, web design/dev, e-commerce…)","Branding (identité, naming, design system, motion…)","« Triforce » (ops + design + dev)"],
    forces:["« Le design et le code ne sont que des outils, ce qui compte c'est l'équipe »","Ton de marque fort, joueur, assumé","Preuve par les awards (compteur 295)","Concept propriétaire mémorable (« Triforce »)"],
    faiblesses:["Peu de bénéfices business chiffrés (vend le prestige)","CTA de conversion faibles","Vocabulaire vague (« meaningful, distinctive ») sans preuve"],
    motsRecup:["« Le code et le design ne sont que des outils. Ce qui change tout, c'est l'équipe »","Concept d'intégration multi-métiers (façon « Triforce »)","« Sur-mesure, taillé pour vous et votre audience »"] },

  { id:"akaru", name:"Akaru", verticale:"Design", pays:"France (Lyon)", resultatScore:4, verdict:"Bénéfices émotionnels (voix)", prix:"Non",
    heroVO:"Akaru, agence web créative à Lyon — l'amour du détail qui tue.",
    heroFR:"Akaru, agence web créative à Lyon — l'amour du détail qui tue.",
    lexique:"créatif, sur-mesure, personnalité, audace, « le client n'est pas roi », anti-déjà-vu.",
    offres:["01 Stratégie & Conseil","02 Direction Artistique","03 Site e-commerce (Shopify/Headless)","04 Site Vitrine","05 Expérience Digitale"],
    forces:["Voix de marque ultra-distinctive (ton parlé, punchlines)","Manifeste de valeurs (« le roi, c'est votre utilisateur »)","Awards comme colonne vertébrale de la preuve créative","Équipe nommée avec visages/rôles ; expertises numérotées"],
    faiblesses:["Peu de résultats business chiffrés (que du créatif/awards)","Ton parfois trop « posture »/cryptique","CTA faibles, parcours de conversion peu explicite"],
    motsRecup:["Adopter une VRAIE voix de marque avec punchlines assumées","« Des sites/systèmes sur mesure avec de la personnalité »","Manifeste court : une prise de position (« la créa qui vend »)"] },

  { id:"kab", name:"KAB Agency", verticale:"Influence (hors sujet)", pays:"—", resultatScore:4, verdict:"Bénéfices (sans preuve)", prix:"Non",
    heroVO:"Curating the next era of creator-brand partnerships.",
    heroFR:"Curation de la prochaine ère des partenariats créateurs-marques.",
    lexique:"authenticité, autorité culturelle, « quiet filter », longévité, alignement.",
    offres:["Strategic Management","Brand Development","For Brands"],
    forces:["Punchline « Arrêtez de chercher des métriques, cherchez de l'influence »","Process 01/02/03 clair (Alignment → Execution → Measurement)","Ton premium/sélectif (rareté, « applications Q3/Q4 »)"],
    faiblesses:["Aucune preuve sociale (ni logo, ni chiffre, ni témoignage)","Métier hors périmètre Kasper (influence/talent)","Refus des « metrics » = à contre-courant de notre discours ROI"],
    motsRecup:["Triptyque « Alignement → Exécution → Mesure » (+ KPIs chez nous)","Effet de rareté/sélection (« places limitées ce trimestre »)","À RETOURNER : nous prouvons PAR les métriques"] },

  { id:"bakery", name:"Bakery", verticale:"Créa/pub", pays:"US (Austin)", resultatScore:3, verdict:"Créatif/culturel", prix:"Non",
    heroVO:"make things people want.",
    heroFR:"fabriquer des choses que les gens veulent.",
    lexique:"make, independent, creative agency, AOR, désir/culture/craft.",
    offres:["Branding / rebrand","Campagnes créatives","Agency of Record (AOR)"],
    forces:["Hero mémorable « make things people want » + animation de mots","Preuve par awards + gains de comptes (« Agency of the Year »)","Ton et énergie très identitaires"],
    faiblesses:["Aucune offre lisible ni prix","Zéro discours ROI/performance","Cible & marché différents (pub US notoriété)"],
    motsRecup:["Accroche courte universelle : « On construit des boutiques que les gens veulent »","Animation de mots en hero pour montrer le multi-services","Preuve par récompenses + jalons de croissance"] },

  { id:"finsweet", name:"Finsweet", verticale:"Code (Webflow)", pays:"US", resultatScore:3, verdict:"Features / technique", prix:"Partiel",
    heroVO:"We build the websites and web apps behind high-growth B2B.",
    heroFR:"Nous construisons les sites et web apps derrière le B2B en forte croissance.",
    lexique:"scalable, maintainable, reliable, « extension of your team », HIPAA, custom apps.",
    offres:["Branding","Design & Strategy","Web Development","SEO/CRO & Growth","Integrations","AI & Automation","Long-Term Relationship","Enterprise"],
    forces:["Hero ultra-clair (QUOI + POUR QUI)","« Extension of your team » / modèle intégré","Preuve par l'écosystème (outils gratuits Attributes/Client-First)","Transparence : devis self-service (services × heures → contrat)"],
    faiblesses:["Trop de jargon technique, froid, peu d'émotion","Mur de 20+ témoignages quasi identiques","Peu de storytelling (le POURQUOI)"],
    motsRecup:["« Une extension de votre équipe » / « modèle intégré »","Configurateur / devis en libre-service comme différenciateur","Crédibiliser l'expertise par des ressources/outils gratuits"] },

  { id:"cherami", name:"Cher Ami", verticale:"Créa", pays:"France (Lyon)", resultatScore:2, verdict:"Beauté / valeurs", prix:"Non",
    heroVO:"We elevate the content creation for Brands & Businesses.",
    heroFR:"Nous élevons la création de contenu pour les marques et les entreprises.",
    lexique:"création, élégance, « amitié avec les marques », collectif, RSE/éco-conception.",
    offres:["(pas d'offres nommées — déduites des tags projets : UX, 3D, Brand Content, E-commerce…)"],
    forces:["Métaphore de marque « l'ami » filée (chaleureux, mémorable)","Axe engagement/RSE concret (ECOVADIS Platinium, mécénat)","Portfolio de marques fortes (Dior, Netflix, Veuve Clicquot)"],
    faiblesses:["Copy très pauvre, pas d'offres nommées, pas de CTA clair","Aucune preuve de résultats (ni chiffres, ni témoignages)","Positionnement flou (« pour qui / pour quel gain ? »)"],
    motsRecup:["Métaphore relationnelle chaleureuse (agence « partenaire/ami »)","« Expériences élégantes et mémorables » (+ bénéfice business)","Contre-exemple : NE PAS faire un site beau mais muet"] },

  { id:"okeystudio", name:"Okey Studio", verticale:"Code/créa", pays:"France (Toulouse)", resultatScore:2, verdict:"Expérience / craft", prix:"Non",
    heroVO:"A French creative digital studio — made with a lot of love and a bit of code.",
    heroFR:"Un studio créatif et digital français — avec beaucoup d'amour et un peu de code.",
    lexique:"creative, interactive, customized, unique, « a lot of love and a bit of code ».",
    offres:["Création de sites sur-mesure interactifs (offre unique, non packagée)"],
    forces:["Ton chaleureux différenciant (« with a lot of love and a bit of code »)","Le site EST la démo (l'interactivité prouve la compétence)","Positionnement clair en une phrase"],
    faiblesses:["Contenu quasi inexistant (mono-page JS), SEO faible","Aucune offre, aucun prix, aucun process","Zéro discours ROI/business"],
    motsRecup:["« Avec beaucoup d'amour et un peu de code » (humaniser la tech/IA)","« Le site prouve la compétence » (soigner l'interactivité du nôtre)","À COMPLÉTER par offres/prix/preuve de résultat"] },

  { id:"murmure", name:"Murmure", verticale:"Design", pays:"France (Caen)", resultatScore:2, verdict:"Œuvre / artisanat", prix:"Non",
    heroVO:"Studio de direction artistique, de design graphique et numérique indépendant.",
    heroFR:"Studio de direction artistique, de design graphique et numérique indépendant.",
    lexique:"sur-mesure, pérenne, sensibilité, souci du détail, artisans, « montrer plutôt que dire ».",
    offres:["Direction artistique","Identité visuelle","Design graphique/éditorial","Sites (WordPress) sur-mesure"],
    forces:["Parti-pris fort : « moins de texte, plus d'images »","Ton humain et sincère (« nos petites mains d'artisans »)","Références culturelles prestigieuses qui font autorité"],
    faiblesses:["Zéro discours business/ROI","Pas de CTA ni de tunnel de conversion","Pas de prix, pas d'offres lisibles"],
    motsRecup:["« Sur-mesure et pérenne » (qualité durable vs templates)","Ton humain/artisan à DOSER (sans perdre le ROI)","⚠️ à NE PAS copier : l'absence de CTA/prix/promesse"] },
];

/* ------- Reco « Tinder » : à trancher (👍 on garde / 🤔 peut-être / 👎 pas pour nous) ------- */
window.COPY_RECOS = [
  { id:"prix", cat:"Pricing", titre:"Afficher des fourchettes de prix", pourquoi:"17/19 concurrents cachent leurs prix. Seuls Ramotion et Digidop les montrent — et c'est un aimant à confiance + un filtre à leads. Afficher « à partir de… » nous démarque immédiatement.", source:"Ramotion, Digidop" },
  { id:"chiffres", cat:"Preuve", titre:"Traduire chaque livrable en chiffre business", pourquoi:"La mécanique n°1 de Ramotion et Bold : jamais un adjectif seul, toujours un chiffre (+X% conversion, ROAS, CA). C'est ce qui sépare les 4 sérieux des 15 qui vendent du beau.", source:"Ramotion, Bold, Digidop" },
  { id:"hero-moment", cat:"Hero", titre:"Hero « l'agence que [X] appelle quand [problème] »", pourquoi:"Format de Refokus, ultra-relatable. Ex : « L'agence que les e-commerçants appellent quand leur marque bride leurs ventes. » Parle au besoin, pas au service.", source:"Refokus" },
  { id:"voix", cat:"Ton", titre:"Adopter une vraie voix de marque (punchlines)", pourquoi:"Akaru, Locomotive, Cher Ami sont mémorables par leur ton. La plupart des concurrents « perf » sont corporate et froids (Ramotion, Finsweet). On peut être le seul à être sérieux ET vivant.", source:"Akaru, Locomotive" },
  { id:"ia-angle", cat:"IA", titre:"Angle IA = « un système qui agit à votre place »", pourquoi:"Edgar Allan a une accroche IA forte (« ce que l'IA dit de vous… »). Notre version : pas du buzzword, mais des systèmes automatiques (Hermes) qui surveillent/alertent/rapportent. On l'utilise déjà sur CYKL.", source:"Edgar Allan (adapté)" },
  { id:"bandeau", cat:"Preuve", titre:"Bandeau de chiffres agence dans le hero", pourquoi:"« 1 Md$ levés · 6 Md$ d'exits » chez Ramotion positionne en partenaire de croissance dès la 1re seconde. Nous : « X marques · +X% trafic CYKL · ROAS moyen X ».", source:"Ramotion" },
  { id:"extension", cat:"Ton", titre:"« Une extension de votre équipe »", pourquoi:"Repris par Digidop, Eastside, Finsweet : vend la relation et la durée, pas un one-shot. Colle à notre modèle (accompagnement + Kasper OS).", source:"Digidop, Eastside, Finsweet" },
  { id:"offre-structure", cat:"Offres", titre:"Structure d'offre « 1 phrase-bénéfice + 2 cas »", pourquoi:"Instrument et Cuberto : chaque service = un titre-bénéfice + preuve. Simplifie notre multi-services en blocs limpides (anti-fouillis, ta crainte n°1).", source:"Instrument, Cuberto, Digidop" },
  { id:"faq", cat:"Preuve", titre:"FAQ qui tue les objections", pourquoi:"Cuberto et Digidop répondent aux vraies peurs (délais, budget, « ils font tout = ils maîtrisent rien », lock-in). Rassure ET référence (SEO).", source:"Cuberto, Digidop" },
  { id:"triptyque", cat:"Positionnement", titre:"Triptyque d'action « Concevoir · Lancer · Piloter »", pourquoi:"« design, develop and grow » (We Make Websites) est mémorable et rythmé. Notre fil rouge tient en 3 verbes qui unifient les 4 piliers.", source:"We Make Websites" },
  { id:"manifeste", cat:"Ton", titre:"Un manifeste / prise de position en points numérotés", pourquoi:"Refokus et Akaru posent une opinion qui attire les bons clients. Ex : « La perf sans le blabla », « On vous dit ce qu'on pense ».", source:"Refokus, Akaru" },
  { id:"checklist", cat:"Offres", titre:"Checklist « Vous êtes au bon endroit si… »", pourquoi:"Edgar Allan qualifie le prospect en listant ses douleurs. On récupère directement les douleurs de notre ICP (rupture, ROAS qui fond, dimanche soir…).", source:"Edgar Allan" },
  { id:"leadmagnet", cat:"Offres", titre:"Lead magnet = diagnostic/audit gratuit en CTA principal", pourquoi:"Edgar Allan (« AI Brand Score ») et Eastside (guide SEO) capturent par la valeur. Notre Audit Croissance peut avoir une version « mini-audit gratuit ».", source:"Edgar Allan, Eastside" },
  { id:"recurrent", cat:"Offres", titre:"Nommer une offre récurrente packagée (Kasper OS abo)", pourquoi:"« Team Extension » (16,8K$/mo) chez Ramotion, « Ongoing Success » chez We Make Websites : le récurrent packagé et nommé. Le nôtre = Kasper OS en abonnement.", source:"Ramotion, We Make Websites" },
  { id:"endossement", cat:"Preuve", titre:"Chercher un endossement fort (Meta/Shopify/partenaire)", pourquoi:"La citation du Président de Shopify (We Make Websites, Bold) est la preuve la plus forte du panel. Un badge partenaire Meta/Shopify + une citation = confiance immédiate.", source:"We Make Websites, Bold" },
  { id:"equipe", cat:"Ton", titre:"Assumer l'équipe nommée (visages + rôles)", pourquoi:"Akaru et Locomotive humanisent en montrant l'équipe. Colle à notre positionnement « 2 fondateurs seniors + systèmes », pas une grosse agence anonyme.", source:"Akaru, Locomotive" },
  { id:"concept", cat:"Positionnement", titre:"Un nom propriétaire pour notre méthode multi-services", pourquoi:"« Triforce » (Locomotive), « Answer-Ready Branding » (Edgar Allan) : un concept nommé rend l'intégration mémorable. Ex : notre méthode « Concevoir→Lancer→Piloter » ou « Kasper OS ».", source:"Locomotive, Edgar Allan" },
  { id:"anti-superlatif", cat:"Ton", titre:"Bannir les superlatifs auto-proclamés", pourquoi:"« World's most trusted », « n°1 » sans source (Eastside, Digidop) sonnent creux. On remplace chaque superlatif par un chiffre ou un fait vérifiable.", source:"Anti-Eastside" },
];

/* ------- Synthèse copy (résumé actionnable) ------- */
window.COPY_SYNTHESE = {
  constat:"Sur 19 concurrents, seuls 4 vendent un résultat prouvé (Ramotion, Digidop, Cuberto, Edgar Allan). Les 15 autres vendent de l'esthétique et des awards. Notre créneau : le résultat prouvé — mais avec une arme unique : la preuve vécue (CYKL) + des systèmes automatiques (Kasper OS).",
  motsUtiliser:["résultat","preuve","mesuré / chiffré","croissance","ventes","marge","ROAS","conversion","système / systèmes automatiques","piloter","concevoir → lancer → piloter","tranquillité","contrôle","à votre image","partenaire / extension de votre équipe","on l'utilise nous-mêmes (CYKL)"],
  motsBannir:["AI-powered","solutions innovantes","maximiser votre potentiel","sur-mesure (sans preuve)","classe mondiale / n°1 (auto-proclamé)","AEO/GEO/CRO empilés sans traduction","on fait de beaux sites"],
  ressenti:[
    { t:"Confiance / sérieux", d:"par la preuve chiffrée et les prix affichés (« ils assument, ils prouvent »)." },
    { t:"Soulagement / tranquillité", d:"« ils portent la charge, je récupère mes soirées » (Kasper OS, systèmes)." },
    { t:"Contrôle", d:"« je sais enfin ce qui marche, je décide avec des données »." },
    { t:"Proximité", d:"« ils sont e-commerçants comme moi, ils parlent ma langue » (CYKL, voix praticien)." },
    { t:"Fierté / ambition maîtrisée", d:"« une marque au niveau de mon produit, je grandis sans que ça casse »." }
  ],
  piliers:[
    { pilier:"Design & Branding", feature:"« On fait des logos, des sites, une identité »", benefice:"« Une marque au niveau de votre produit — qui inspire confiance et fait vendre, pas juste qui fait joli. »" },
    { pilier:"Media Buying / Acquisition", feature:"« On gère vos Meta Ads »", benefice:"« Des ventes qui ne s'arrêtent pas quand vous coupez le budget. Chaque euro tracé, un ROAS que vous comprenez. »" },
    { pilier:"IA / Kasper OS", feature:"« On utilise l'IA / on est AI-powered »", benefice:"« Un système qui surveille, alerte et rapporte à votre place. Vous récupérez vos dimanches soir. »" },
    { pilier:"E-commerce & Shopify", feature:"« On développe votre boutique Shopify »", benefice:"« Vendre plus sans que ça casse — stock, cash, support. »" }
  ]
};

/* ------- Questions à G pour verrouiller le copy (réponses = direction) ------- */
window.COPY_QUESTIONS = [
  { id:"q1", q:"Quel niveau de voix de marque on assume ?", why:"De « corporate sérieux » (Ramotion) à « punchy avec des punchlines » (Akaru). Mon avis : sérieux MAIS vivant — on peut être les seuls à être crédibles ET pas chiants. Dis-moi jusqu'où on pousse le ton." },
  { id:"q2", q:"Quelles vraies métriques on peut afficher ? (CYKL + missions)", why:"C'est LE bloc qui manque partout. Donne-moi les chiffres réels : trafic organique CYKL, conversion, CA/marge, ROAS de tes campagnes Meta, résultats d'anciens clients. Sans ça, on reste au niveau des 15 qui vendent du vent." },
  { id:"q3", q:"On affiche quelles fourchettes de prix ?", why:"Pour se démarquer (17/19 opaques). Il me faut : prix plancher Audit (~990€ ?), fourchette Mission, modèle Kasper OS (install + abo/mois), tarif media buying (% du budget ou forfait). Donne des bornes, même larges." },
  { id:"q4", q:"On garde les Sprints Design comme produit d'appel ?", why:"Branding Sprint, Landing, Pitch Deck. Oui = on assume le multi-services et on capte des leads design. Non = on concentre sur growth/e-com/IA. Ton call." },
  { id:"q5", q:"Ton wording perso : des formules/expressions à toi ?", why:"Donne-moi 3-5 phrases que TU dirais à un prospect (comment tu expliques ce qu'on fait, tes tics de langage). On construit la voix Kasper à partir de ta vraie parole, pas d'un template." },
  { id:"q6", q:"On a un endossement mobilisable ?", why:"Badge partenaire Meta/Shopify ? Une citation d'un client connu, d'un partenaire ? C'est la preuve la plus forte du panel (cf. citation du Président de Shopify chez les concurrents Shopify)." },
  { id:"q7", q:"On nomme notre méthode ?", why:"« Triforce », « Answer-Ready Branding »… un concept nommé marque les esprits. On garde « Concevoir → Lancer → Piloter », ou on invente un nom de méthode/framework Kasper ?" },
  { id:"q8", q:"Quelles expériences/preuves d'acquisition tu peux documenter ?", why:"Pour le pilier Media Buying : budgets gérés, ROAS obtenus, verticales (lead gen, e-com, SaaS). Un cas chiffré anonymisé suffit à crédibiliser tout le pilier." }
];
